using FluentMigrator;

namespace TauCode.Db.Tests.Data
{
    [Migration(0)]
    public class M0_Baseline : AutoReversingMigration
    {
        public override void Up()
        {
            this.Create.Table("user")
                .WithColumn("id")
                    .AsGuid()
                    .NotNullable()
                    .PrimaryKey("pk_user")
                .WithColumn("name")
                    .AsString(200)
                    .NotNullable()
                .WithColumn("birthday")
                    .AsDateTime()
                    .NotNullable()
                .WithColumn("gender")
                    .AsBoolean() // 0 - male, 1 - female.
                    .NotNullable()
                .WithColumn("picture")
                    .AsBinary(10000)
                    .Nullable();

            this.Create.Table("user_info")
                .WithColumn("id")
                    .AsGuid()
                    .NotNullable()
                    .PrimaryKey("pk_userInfo")
                .WithColumn("user_id")
                    .AsGuid()
                    .NotNullable()
                    .ForeignKey("fk_userInfo_user", "user", "id")
                .WithColumn("tax_number")
                    .AsFixedLengthAnsiString(10)
                    .NotNullable()
                .WithColumn("code")
                    .AsFixedLengthString(20)
                    .NotNullable()
                .WithColumn("ansi_name")
                    .AsAnsiString(200)
                    .NotNullable()
                .WithColumn("ansi_description")
                    .AsAnsiString(int.MaxValue)
                    .NotNullable()
                .WithColumn("unicode_description")
                    .AsString(int.MaxValue)
                    .NotNullable()
                .WithColumn("height")
                    .AsFloat()
                    .NotNullable()
                .WithColumn("weight")
                    .AsDouble()
                    .NotNullable()
                .WithColumn("salary")
                    .AsCurrency()
                    .NotNullable()
                .WithColumn("rating")
                    .AsDecimal(19, 7)
                    .NotNullable()
                .WithColumn("num8")
                    .AsByte()
                    .NotNullable()
                .WithColumn("num16")
                    .AsInt16()
                    .NotNullable()
                .WithColumn("num32")
                    .AsInt32()
                    .NotNullable()
                .WithColumn("num64")
                    .AsInt64()
                    .NotNullable()
                .WithColumn("preferred_time")
                    .AsTime()
                    .NotNullable();
        }
    }
}
