CREATE TABLE the_user(
    [id] uniqueidentifier NOT NULL,
    "login" "nvarchar"(20) NOT NULL,
    email [int] NOT NULL,
    password_hash [char](30) NOT NULL,
    optional1 bigint NULL,
    optional2 int NOT NULL,
    amount1 decimal,
    amount2 decimal NULL,
    amount3 decimal NOT NULL,
    amount4 "decimal"(10) NULL,
    amount5 [decimal](10, 2) NULL,
    credit1 numeric,
    credit2 "numeric"(10) NOT NULL,
    credit3 [numeric](10, 2) NULL,
    PRIMARY KEY("id"))
